spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:~/test
    username: sa
    password:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

